name: node-luma-pwa
type: nodejs:10

dependencies:
    nodejs:
        pm2: '^4.2.1'

web:
    commands:
        start: 'pm2 start npm --name "next" -- start:magento-cloud  --no-daemon'

hooks:
    build: |
        npm install
        npm run build
build:
    flavor: none

mounts:
    run:
        source: local
        source_path: run

variables:
    env:
        MAGENTO_URL: https://admin:a6terwtbk67os@carlos-233-3h6p5qa-a6terwtbk67os.demo.magentosite.cloud
        CONTENT_HOME_PAGE_ID: 20
        CONTENT_PARENT_CATEGORIES_ID: 2
        CONTENT_FOOTER_BLOCK_ID: footer

disk: 4096
