name: node-luma-pwa
type: nodejs:10

dependencies:
    nodejs:
        pm2: '^4.2.1'

web:
    commands:
        start: 'NODE_ENV=production PM2_HOME=/app/run pm2 start server/index.js --no-daemon'

hooks:
    build: |
        npm install
        npm run build
build:
    flavor: none

variables:
    env:
        PORT: 80
        # Magento  Instance Config
        MAGENTO_URL: https://admin:a6terwtbk67os@carlos-233-3h6p5qa-a6terwtbk67os.demo.magentosite.cloud
        CONTENT_HOME_PAGE_ID: 20
        CONTENT_PARENT_CATEGORIES_ID: 2
        CONTENT_FOOTER_BLOCK_ID: footer

disk: 512
