name: node-luma-pwa
type: nodejs:10

dependencies:
    nodejs:
        yarn: '1.19.*'

web:
    commands:
        start: yarn start

hooks:
    build: |
        yarn install
        yarn build
build:
    flavor: none

variables:
    env:
        PORT: 80

disk: 512
