name: node-luma-pwa
type: nodejs:10

dependencies:
    nodejs:
        next: ^9.2.0

web:
    commands:
        start: 'next start -p $PORT'

hooks:
    build: |
        npm install
        npm run build

build:
    flavor: none

mounts:
    run:
        source: local
        source_path: run

variables:
    env:
        MAGENTO_URL: https://admin:a6terwtbk67os@develop-sr3snxi-a6terwtbk67os.demo.magentosite.cloud/

disk: 4096
