name: node-luma-pwa
type: nodejs:10

dependencies:
    nodejs:
        yarn: '1.19.*'

web:
    commands:
        start: yarn start
    locations:
        '/':
            passthru: false
            root: 'static'
            allow: false
            rules:
                '^manifest.webmanifest$':
                    allow: true
                '^static\/.*':
                    allow: true

hooks:
    build: |
        yarn install
        yarn build
build:
    flavor: none

variables:
    env:
        PORT: 80
        # Magento  Instance Config
        MAGENTO_URL: https://admin:a6terwtbk67os@carlos-233-3h6p5qa-a6terwtbk67os.demo.magentosite.cloud
        CONTENT_HOME_PAGE_ID: 20
        CONTENT_PARENT_CATEGORIES_ID: 2
        CONTENT_FOOTER_BLOCK_ID: footer

disk: 512
