name: node-luma-pwa
type: nodejs:10

dependencies:
    nodejs:
        next: ^9.2.0

web:
    commands:
        start: 'next start -p $PORT'

hooks:
    build: |
        npm install
        MAGENTO_URL=$MAGENTO_URL CATEGORIES_PARENT_ID=$CATEGORIES_PARENT_ID FOOTER_BLOCK_ID=$FOOTER_BLOCK_ID next build
build:
    flavor: none

mounts:
    run:
        source: local
        source_path: run

disk: 4096
