name: node-luma-pwa
type: nodejs:10

dependencies:
    nodejs:
        next: ^9.2.0

web:
    commands:
        start: 'next start -p $PORT'

hooks:
    build: |
        npm install
        npm run build
build:
    flavor: none

mounts:
    run:
        source: local
        source_path: run

# variables:
#     env:
#         magentoUrl: https://admin:a6terwtbk67os@carlos-233-3h6p5qa-a6terwtbk67os.demo.magentosite.cloud
#         homePageId: 20
#         categoryParentId: 2
#         footerBlockId: footer

disk: 4096
