name: node-luma-pwa
type: nodejs:10

dependencies:
    nodejs:
        next: ^9.2.0

web:
    commands:
        start: 'next start -p $PORT'

hooks:
    build: |
        touch .env
        npm install
        npm run build

build:
    flavor: none

mounts:
    run:
        source: local
        source_path: run

    app:
        source: local
        source_path: app

disk: 4096
