name: node-luma-pwa
type: nodejs:10

dependencies:
    nodejs:
        next: ^9.2.0

web:
    commands:
        start: 'next start -p $PORT'

hooks:
    build: |
        touch .env 
        chmod 777 .env
        npm install
        npm run build

    deploy: |
        echo MAGENTO_URL=$MAGENTO_URL > .env

build:
    flavor: none

mounts:
    run:
        source: local
        source_path: run

disk: 4096
