name: node-luma-pwa
type: nodejs:10

dependencies:
    nodejs:
        next: ^9.2.0

web:
    commands:
        start: 'next start -p $PORT'

hooks:
    build: |
        npm install
        next build

build:
    flavor: default

mounts:
    run:
        source: local
        source_path: run

disk: 4096
