version: '3.0'
services:
  storystore-pwa:
    build:
      context: .
  sut:
    image: curlimages/curl
    entrypoint: /bin/sh
    command: -c 'sleep 10; curl -fail http://storystore-pwa:3000'
    depends_on:
      - storystore-pwa
