name: CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install, build
        run: |
          npm install
          npm run build
        env:
          MAGENTO_URL: ${{ secrets.STORYSTOREBACKEND }}
          HOME_PAGE_ID: home-luma-ui
          DEMO_MODE: true
      - name: npm run
        run: |
          npm start &
          npm_pid=$!
          sleep 5
          echo khb-curling
          curl -I http://localhost:3000/
          kill $npm_pid
          env
          echo khb-killing
        env:
          MAGENTO_URL: ${{ secrets.STORYSTOREBACKEND }}
          HOME_PAGE_ID: home-luma-ui
          DEMO_MODE: true
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.4.x
          lhci autorun